apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        env:
          # Use secret in real usage
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: wealthuser
        - name: MYSQL_PASSWORD
          value: wealthpass
        - name: MYSQL_DATABASE
          value: wealth
